package admin;

import PLC.PLC_Model;
import PLC.PLCpaint;
import PLC.outpot;
import inicio.de.sesion.Acceso;
import inicio.de.sesion.Navegacion;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Luis
 */
public class MenuAdministrador extends javax.swing.JFrame implements PLCpaint{
    public Navegacion navegacion;
   
    public MenuAdministrador(Navegacion navegacion) {
        this.navegacion = navegacion;
        initComponents();
           
        setLocationRelativeTo(null); //se elije en que parte de la pantalla aparecera null (centro)
        //setResizable(false);//evitamos que la pantalla se modifique.
        this.setTitle("Menu Administrador-Inteppco");//titulo a la pantalla.
        setIconImage(new ImageIcon(getClass().getResource("/imgVentanas/logo_1.png")).getImage());
                try{
        BufferedImage imagen =ImageIO.read(MenuAdministrador.class.getResourceAsStream("/imgVentanas/fondo.png"));
        Control_fondo.
        BgBorder borde = new Control_fondo.BgBorder(imagen) ;            
      primario.setBorder(borde);
     
                }
       catch(IOException io){
           
       }
               
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();
        jMenu1 = new javax.swing.JMenu();
        primario = new javax.swing.JPanel();
        tabbedPaneHeader1 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        menuAdmin = new org.edisoncor.gui.panel.PanelTranslucido();
        Menu = new javax.swing.JPanel();
        btn_reportes = new javax.swing.JButton();
        gestion_de_componentes1 = new javax.swing.JButton();
        btn_control_operadores = new javax.swing.JButton();
        imagen1 = new org.edisoncor.gui.panel.PanelImage();
        Operacion = new org.edisoncor.gui.panel.PanelTranslucido();
        sistema = new javax.swing.JPanel();
        Metales = new javax.swing.JLabel();
        dosificadora = new javax.swing.JLabel();
        Banda1 = new javax.swing.JLabel();
        pulverizadora = new javax.swing.JLabel();
        banda2 = new javax.swing.JLabel();
        criva = new javax.swing.JLabel();
        trituradora = new javax.swing.JLabel();
        encender = new javax.swing.JPanel();
        panelRect9 = new org.edisoncor.gui.panel.PanelRect();
        onOff = new javax.swing.JButton();
        jonoff = new javax.swing.JLabel();
        nomeclaruras = new javax.swing.JPanel();
        panelRect10 = new org.edisoncor.gui.panel.PanelRect();
        jLabel13 = new javax.swing.JLabel();
        panelRect11 = new org.edisoncor.gui.panel.PanelRect();
        panelRect12 = new org.edisoncor.gui.panel.PanelRect();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelRect13 = new org.edisoncor.gui.panel.PanelRect();
        panelRect14 = new org.edisoncor.gui.panel.PanelRect();
        jLabel16 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPaneHeader1.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPaneHeader1.setColorDeBorde(new java.awt.Color(255, 255, 255));

        menuAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(219, 237, 223), new java.awt.Color(133, 178, 163)));
        menuAdmin.setColorPrimario(new java.awt.Color(219, 237, 223));
        menuAdmin.setColorSecundario(new java.awt.Color(133, 178, 163));

        Menu.setOpaque(false);

        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes-normal.png"))); // NOI18N
        btn_reportes.setBorder(null);
        btn_reportes.setBorderPainted(false);
        btn_reportes.setContentAreaFilled(false);
        btn_reportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes-press.png"))); // NOI18N
        btn_reportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes-over.png"))); // NOI18N
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        gestion_de_componentes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/componentes-normal.png"))); // NOI18N
        gestion_de_componentes1.setBorder(null);
        gestion_de_componentes1.setBorderPainted(false);
        gestion_de_componentes1.setContentAreaFilled(false);
        gestion_de_componentes1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/componentes-press.png"))); // NOI18N
        gestion_de_componentes1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/componentes-over.png"))); // NOI18N
        gestion_de_componentes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestion_de_componentes1ActionPerformed(evt);
            }
        });

        btn_control_operadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal-normal.png"))); // NOI18N
        btn_control_operadores.setBorder(null);
        btn_control_operadores.setBorderPainted(false);
        btn_control_operadores.setContentAreaFilled(false);
        btn_control_operadores.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal-press.png"))); // NOI18N
        btn_control_operadores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal-over.png"))); // NOI18N
        btn_control_operadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_control_operadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_control_operadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gestion_de_componentes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_control_operadores)
                .addGap(4, 4, 4)
                .addComponent(btn_reportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestion_de_componentes1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgVentanas/icono-pantalla.png"))); // NOI18N

        javax.swing.GroupLayout imagen1Layout = new javax.swing.GroupLayout(imagen1);
        imagen1.setLayout(imagen1Layout);
        imagen1Layout.setHorizontalGroup(
            imagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        imagen1Layout.setVerticalGroup(
            imagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuAdminLayout = new javax.swing.GroupLayout(menuAdmin);
        menuAdmin.setLayout(menuAdminLayout);
        menuAdminLayout.setHorizontalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAdminLayout.createSequentialGroup()
                .addGap(0, 1125, Short.MAX_VALUE)
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(menuAdminLayout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuAdminLayout.setVerticalGroup(
            menuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAdminLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPaneHeader1.addTab("Menú", menuAdmin);

        Operacion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(219, 237, 223), new java.awt.Color(133, 178, 163)));
        Operacion.setColorPrimario(new java.awt.Color(219, 237, 223));
        Operacion.setColorSecundario(new java.awt.Color(104, 159, 141));

        sistema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sistema.setOpaque(false);
        sistema.setPreferredSize(new java.awt.Dimension(1160, 425));
        sistema.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Metales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sensor.png"))); // NOI18N
        sistema.add(Metales, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        dosificadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dosificadora.png"))); // NOI18N
        sistema.add(dosificadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        Banda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda.png"))); // NOI18N
        Banda1.setToolTipText("");
        sistema.add(Banda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        pulverizadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulverizadora.png"))); // NOI18N
        sistema.add(pulverizadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        banda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda.png"))); // NOI18N
        sistema.add(banda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        criva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dronel.png"))); // NOI18N
        sistema.add(criva, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        trituradora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trituradora.png"))); // NOI18N
        sistema.add(trituradora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        encender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        encender.setOpaque(false);

        panelRect9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRect9.setAnchoDeBorde(2.0F);
        panelRect9.setAnchoDeSegundoBorde(2.0F);
        panelRect9.setColorDeBorde(java.awt.Color.white);
        panelRect9.setColorDeSegundoBorde(java.awt.Color.lightGray);
        panelRect9.setColorPrimario(new java.awt.Color(204, 204, 204));
        panelRect9.setColorSecundario(new java.awt.Color(153, 153, 153));

        onOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/up_02.png"))); // NOI18N
        onOff.setContentAreaFilled(false);
        onOff.setFocusPainted(false);
        onOff.setFocusable(false);
        onOff.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/donw_02.png"))); // NOI18N
        onOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOffActionPerformed(evt);
            }
        });

        jonoff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jonoff.setText("   Encender");

        javax.swing.GroupLayout panelRect9Layout = new javax.swing.GroupLayout(panelRect9);
        panelRect9.setLayout(panelRect9Layout);
        panelRect9Layout.setHorizontalGroup(
            panelRect9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRect9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRect9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jonoff, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(onOff, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRect9Layout.setVerticalGroup(
            panelRect9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRect9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jonoff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onOff)
                .addContainerGap())
        );

        javax.swing.GroupLayout encenderLayout = new javax.swing.GroupLayout(encender);
        encender.setLayout(encenderLayout);
        encenderLayout.setHorizontalGroup(
            encenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRect9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        encenderLayout.setVerticalGroup(
            encenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRect9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nomeclaruras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nomeclaruras.setOpaque(false);

        panelRect10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRect10.setAnchoDeBorde(2.0F);
        panelRect10.setAnchoDeSegundoBorde(2.0F);
        panelRect10.setColorDeBorde(java.awt.Color.white);
        panelRect10.setColorDeSegundoBorde(java.awt.Color.lightGray);
        panelRect10.setColorPrimario(new java.awt.Color(204, 204, 204));
        panelRect10.setColorSecundario(new java.awt.Color(153, 153, 153));
        panelRect10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Error en Componente.");
        panelRect10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        panelRect11.setAnchoDeBorde(2.0F);
        panelRect11.setAnchoDeSegundoBorde(1.0F);
        panelRect11.setColorDeBorde(new java.awt.Color(102, 102, 102));
        panelRect11.setColorPrimario(new java.awt.Color(255, 153, 153));
        panelRect11.setColorSecundario(new java.awt.Color(255, 0, 0));
        panelRect11.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout panelRect11Layout = new javax.swing.GroupLayout(panelRect11);
        panelRect11.setLayout(panelRect11Layout);
        panelRect11Layout.setHorizontalGroup(
            panelRect11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        panelRect11Layout.setVerticalGroup(
            panelRect11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelRect10.add(panelRect11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        panelRect12.setAnchoDeBorde(2.0F);
        panelRect12.setAnchoDeSegundoBorde(1.0F);
        panelRect12.setColorDeBorde(new java.awt.Color(102, 102, 102));
        panelRect12.setColorPrimario(new java.awt.Color(255, 255, 102));
        panelRect12.setColorSecundario(new java.awt.Color(255, 153, 0));
        panelRect12.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout panelRect12Layout = new javax.swing.GroupLayout(panelRect12);
        panelRect12.setLayout(panelRect12Layout);
        panelRect12Layout.setHorizontalGroup(
            panelRect12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        panelRect12Layout.setVerticalGroup(
            panelRect12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelRect10.add(panelRect12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Atención");
        panelRect10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Sistema Funcionando.");
        panelRect10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        panelRect13.setAnchoDeBorde(2.0F);
        panelRect13.setAnchoDeSegundoBorde(1.0F);
        panelRect13.setColorDeBorde(new java.awt.Color(102, 102, 102));
        panelRect13.setColorPrimario(new java.awt.Color(102, 255, 102));
        panelRect13.setColorSecundario(new java.awt.Color(0, 153, 0));
        panelRect13.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout panelRect13Layout = new javax.swing.GroupLayout(panelRect13);
        panelRect13.setLayout(panelRect13Layout);
        panelRect13Layout.setHorizontalGroup(
            panelRect13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        panelRect13Layout.setVerticalGroup(
            panelRect13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelRect10.add(panelRect13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        panelRect14.setAnchoDeBorde(2.0F);
        panelRect14.setAnchoDeSegundoBorde(1.0F);
        panelRect14.setColorDeBorde(new java.awt.Color(102, 102, 102));
        panelRect14.setColorPrimario(new java.awt.Color(204, 204, 204));
        panelRect14.setColorSecundario(new java.awt.Color(102, 102, 102));
        panelRect14.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout panelRect14Layout = new javax.swing.GroupLayout(panelRect14);
        panelRect14.setLayout(panelRect14Layout);
        panelRect14Layout.setHorizontalGroup(
            panelRect14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        panelRect14Layout.setVerticalGroup(
            panelRect14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        panelRect10.add(panelRect14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Sistema Apagado.");
        panelRect10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        javax.swing.GroupLayout nomeclarurasLayout = new javax.swing.GroupLayout(nomeclaruras);
        nomeclaruras.setLayout(nomeclarurasLayout);
        nomeclarurasLayout.setHorizontalGroup(
            nomeclarurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRect10, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        nomeclarurasLayout.setVerticalGroup(
            nomeclarurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRect10, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout OperacionLayout = new javax.swing.GroupLayout(Operacion);
        Operacion.setLayout(OperacionLayout);
        OperacionLayout.setHorizontalGroup(
            OperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OperacionLayout.createSequentialGroup()
                        .addComponent(nomeclaruras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(encender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        OperacionLayout.setVerticalGroup(
            OperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(sistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(OperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeclaruras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneHeader1.addTab("Operación", Operacion);

        javax.swing.GroupLayout primarioLayout = new javax.swing.GroupLayout(primario);
        primario.setLayout(primarioLayout);
        primarioLayout.setHorizontalGroup(
            primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        primarioLayout.setVerticalGroup(
            primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_control_operadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_control_operadoresActionPerformed
       navegacion.openControlDePersonal();
    }//GEN-LAST:event_btn_control_operadoresActionPerformed

    private void gestion_de_componentes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestion_de_componentes1ActionPerformed
        navegacion.openGestioncomponentes();
    }//GEN-LAST:event_gestion_de_componentes1ActionPerformed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        navegacion.openControlDeReportes();
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void onOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOffActionPerformed
        
    }//GEN-LAST:event_onOffActionPerformed

    
    
    @Override
    public  void repaint(PLC_Model plcVariables){
        if(plcVariables.botonEncendido){
            if(plcVariables.banda1){
                Banda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda-ok.png")));
            }else{
                Banda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda.png")));
            }
            if(plcVariables.banda2){
                 banda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda-ok.png")));
            }else{
                banda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda.png")));
            }
            if(plcVariables.blower){

            }
            if(plcVariables.dosificadora){
                dosificadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dosificadora-ok.png")));
            }else{
                dosificadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dosificadora.png")));
            }
            if(plcVariables.trituradora){
                trituradora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trituradora-ok.png")));
            }else{
               trituradora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trituradora.png")));
              }
            if(plcVariables.pulverizadora){
                pulverizadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulverizadora-ok.png")));    
            }else{
            pulverizadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulverizadora.png")));
            }
                
            if(plcVariables.criva){
             criva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dronel-ok.png")));
            }else{
            criva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dronel.png")));
            }
            if(plcVariables.dosificadora){

            }
            if(plcVariables.metales){
             Metales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sensor-ok.png")));
            }else{
             Metales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sensor.png")));
            }
            jonoff.setText("Apagar");
             onOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/red-on.png")));
        }else{
             jonoff.setText("Encender");
            onOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/up_02.png")));
            Banda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda.png")));
            banda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda.png")));
             dosificadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dosificadora.png")));
             trituradora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trituradora.png")));
             pulverizadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulverizadora.png")));
             criva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dronel.png")));
        }
        if(plcVariables.sensorBanda1){ 
                Banda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda-error.png")));
            }
        if(plcVariables.sensorBanda2){ 
                banda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banda-error.png")));
            }
        if(plcVariables.sensorBlower){

            }
        if(plcVariables.sensorDosificadora){ 
                dosificadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dosificadora-error.png")));
            }
        if(plcVariables.sensorTrituradora){ 
               trituradora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trituradora-error.png")));
              }
        if(plcVariables.sensorPulverizadora){ 
            pulverizadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulverizadora-error.png")));
            } 
        if(plcVariables.sensorCriva){ 
            criva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dronel-error.png")));
            }
        if(plcVariables.dosificadora){

            }
        if(plcVariables.sensormetales){
             Metales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sensor-error.png")));
            } 
        sistema.repaint();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banda1;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Metales;
    private org.edisoncor.gui.panel.PanelTranslucido Operacion;
    private javax.swing.JLabel banda2;
    private javax.swing.JButton btn_control_operadores;
    private javax.swing.JButton btn_reportes;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JLabel criva;
    private javax.swing.JLabel dosificadora;
    private javax.swing.JPanel encender;
    private javax.swing.JButton gestion_de_componentes1;
    private org.edisoncor.gui.panel.PanelImage imagen1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JLabel jonoff;
    private org.edisoncor.gui.panel.PanelTranslucido menuAdmin;
    private javax.swing.JPanel nomeclaruras;
    public javax.swing.JButton onOff;
    private org.edisoncor.gui.panel.PanelRect panelRect10;
    private org.edisoncor.gui.panel.PanelRect panelRect11;
    private org.edisoncor.gui.panel.PanelRect panelRect12;
    private org.edisoncor.gui.panel.PanelRect panelRect13;
    private org.edisoncor.gui.panel.PanelRect panelRect14;
    private org.edisoncor.gui.panel.PanelRect panelRect9;
    private javax.swing.JPanel primario;
    private javax.swing.JLabel pulverizadora;
    private javax.swing.JPanel sistema;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader1;
    private javax.swing.JLabel trituradora;
    // End of variables declaration//GEN-END:variables
}
